# Generated by Django 4.2.6 on 2023-11-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_students_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='font_size',
        ),
    ]
